import {StyleSheet} from 'react-native';
import * as Colors from './Colors';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.BG_COLOR,
    padding: 20,
    paddingTop: 50,
  },
  titleRow: {},
  title: {
    fontSize: 24,
    fontWeight: '600',
  },
  questionNoRow: {
    marginVertical: 10,
    justifyContent: 'space-between',
    flexDirection: 'row',
    height: 40,
  },
  questionText: {
    textTransform: 'uppercase',
    fontSize: 12,
  },
  progressRow: {
    flexDirection: 'row',
    height: 7,
    marginVertical: 10,
    backgroundColor: Colors.BG_COLOR,
    borderRadius: 20,
    maxWidth: '100%',
  },
  activeColor: {
    width: '18%',
    backgroundColor: Colors.WHITE,
    borderRadius: 20,
  },
  inActiveColor: {
    width: '18%',
    backgroundColor: Colors.ACTIVE_COLOR,
    marginHorizontal: 5,
    borderRadius: 20,
  },
  border: {
    backgroundColor: Colors.LIGHT_BLACK,
    height: 2,
    marginVertical: 10,
  },
  questionRow: {
    marginVertical: 10,
  },
  circleContainer: {
    alignItems: 'center',
    marginVertical: 20,
  },
  circleSlider: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    height: 200,
    width: 200,
    borderWidth: 2,
    borderRadius: 200 / 2,
    borderStyle: 'dashed',
    borderColor: Colors.BLACK,
  },
  childCircle: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    height: 150,
    width: 150,
    borderTopWidth: 0,
    borderRadius: 150 / 2,
    borderColor: Colors.LIGHT_BLACK,
    backgroundColor: Colors.ACTIVE_COLOR,
  },
  smallestCircle: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    height: 120,
    width: 120,
    borderWidth: 1,
    borderRadius: 120 / 2,
    borderColor: Colors.LIGHT_BLACK,
    backgroundColor: Colors.FONT_BLUE,
  },
  circleText: {
    fontSize: 40,
  },
  question: {
    fontSize: 20,
    fontWeight: '600',
  },
  radioRow: {
    marginVertical: 10,
  },
  radioButtonRow: {
    padding: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHT_BLACK,
    marginVertical: 5,
    borderRadius: 8,
    backgroundColor: Colors.WHITE,
  },
  radioLabel: {
    marginLeft: 10,
    fontSize: 16,
    color: Colors.FONT_BLACK,
  },
  nextButton: {
    backgroundColor: Colors.WHITE,
    marginVertical: 20,
    left: 20,
    right: 20,
    borderRadius: 30,
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
  },
  top5: {
    width: 250,
    height: 40,
    backgroundColor: Colors.LIGHT_BLACK,
    borderTopEndRadius: 50,
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 100,
    borderBottomRightRadius: 100,
  },
  top4: {
    marginTop: 20,
    width: 200,
    height: 40,
    backgroundColor: Colors.LIGHT_BLACK,
    borderTopEndRadius: 50,
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 100,
    borderBottomRightRadius: 100,
  },
  top3: {
    marginTop: 20,
    width: 150,
    height: 40,
    backgroundColor: Colors.LIGHT_BLACK,
    borderTopEndRadius: 50,
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 100,
    borderBottomRightRadius: 100,
  },
  top2: {
    marginTop: 20,
    width: 100,
    height: 40,
    backgroundColor: Colors.LIGHT_BLACK,
    borderTopEndRadius: 50,
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 100,
    borderBottomRightRadius: 100,
  },
  top1: {
    marginTop: 20,
    width: 50,
    height: 40,
    backgroundColor: Colors.LIGHT_BLACK,
    borderTopEndRadius: 50,
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 100,
    borderBottomRightRadius: 100,
    borderBottomEndRadius: 100,
    borderBottomStartRadius: 100,
  },
  center: {
    alignSelf: 'center',
  },
});
